import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/Providers";
import Navbar from "@/components/Header";

export const metadata: Metadata = {
  title: "JobVerse.AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gradient-to-br from-slate-50 via-fuchsia-50 to-violet-50`}
      >
        <Providers>
          {/* <Navbar /> */}
          <Navbar />
          <main className="py-[10vh] max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
