import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/Providers";
import Navbar from "@/components/Header";
import { cn } from "@/lib/utils";
import { ClassNameValue } from "tailwind-merge";

export const metadata: Metadata = {
  title: "JobVerse.AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn('bg-gradient-to-br from-slate-50 via-fuchsia-50 to-violet-50', darkMode2)}
      >
        <Providers>
          {/* <Navbar /> */}
          <Navbar />
          <main className="py-[10vh] max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}

const lightMode1 = `bg-gradient-to-br from-slate-50 via-fuchsia-50 to-violet-50`

const darkMode1: ClassNameValue= " dark:from-[#3c0a3d] dark:via-[#050115] dark:to-[#000000]"
const darkMode2 = `dark:from-[#0d3647] dark:via-black dark:to-[#000008]`
