import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/Providers";
import Navbar from "@/components/Header";
import { cn } from "@/lib/utils";
import { ClassNameValue } from "tailwind-merge";

export const metadata: Metadata = {
  title: "Zenith AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Providers>

          <div
            className={'bg-gradient-to-br from-slate-50 via-fuchsia-50 to-violet-50 dark:from-[#0d3647] dark:via-black dark:to-[#000008]'} suppressHydrationWarning>

            <Navbar />
            <main className="py-[10vh] max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              {children}
            </main>
          </div>

        </Providers>
      </body>
    </html>
  );
}
