import { Metadata } from "next";
import ProgressBar from "./ProgressBar";

export const metadata: Metadata = {
    // title: "JobVerse.AI",
    // description: "Generated by create next app",
};

export default async function OnboardingLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <div>
            <ProgressBar currentStep={0}/>
            {children}
        </div>
    );
}
