services:
  fastapi:
    container_name: python-server
    build: .
    restart: always
    ports: 
      - "8000:8000"
    env_file:
      - app/.env
    environment:
      - UPSTASH_URL={UPSTASH_URL}
      - UPSTASH_TOKEN={UPSTASH_TOKEN}
      - HUGGINGFACE_API_KEY={HUGGINGFACE_API_KEY}